import React from "react";
import { PageShell } from "./PageShell";
import { ReportHeader } from "./ReportHeader";
import { List, ClipboardList, Sparkles, Stethoscope, FileText } from "lucide-react";

interface TOCPageProps {
  data: any;
  pageNum: number;
  totalPages: number;
}

const TOC_ITEMS = [
  {
    icon: ClipboardList,
    title: "Page 1: Patient Health Summary",
    description: "Visualization of historical symptom trends and care pillar averages for the selected period.",
  },
  {
    icon: Sparkles,
    title: "Page 2: AI Clinical Insights",
    description: "Detailed categorical findings and critical safety risk assessments synthesized from log data.",
  },
  {
    icon: Stethoscope,
    title: "Page 3: NHS Guidance Alignment",
    description: "Analysis of symptom patterns against official NHS Traumatic Encephalopathy markers.",
  },
  {
    icon: FileText,
    title: "Page 4: Professional Clinician Memo",
    description: "Formal clinical evaluation space and suggested diagnostic next steps for medical review.",
  },
];

export const TOCPage: React.FC<TOCPageProps> = ({ data, pageNum, totalPages }) => {
  return (
    <PageShell 
      pageNum={pageNum} 
      totalPages={totalPages}
      patientName={data.patient.name}
      patientId={data.patient.id}
    >
      <ReportHeader 
        title="Report Overview" 
        subtitle="Table of Contents & Section Descriptions"
        patient={data.patient}
        summary={data.summary}
        periodInfo={{ 
          label: "REPORT PERIOD", 
          value: `${data.period.dateA} — ${data.period.dateB}`,
          sub: `${data.period.entries} symptom logs`
        }}
      />

      <div style={{ marginTop: 40, padding: "0 20px" }}>
        <div style={{ 
          display: "flex", 
          alignItems: "center", 
          gap: 15, 
          marginBottom: 30,
          borderBottom: "2px solid #e2e8f0",
          paddingBottom: 15
        }}>
          <List size={24} color="#0f172a" />
          <h2 style={{ fontSize: 24, fontWeight: 900, color: "#0f172a", margin: 0 }}>Clinical Roadmap</h2>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
          {TOC_ITEMS.map((item, idx) => (
            <div key={idx} style={{ 
              display: "flex", 
              gap: 20, 
              padding: 25, 
              backgroundColor: "#f8fafc", 
              borderRadius: 20,
              border: "1px solid #e2e8f0"
            }}>
              <div style={{ 
                width: 50, 
                height: 50, 
                borderRadius: 15, 
                backgroundColor: "#fff", 
                display: "flex", 
                alignItems: "center", 
                justifyContent: "center",
                boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
                flexShrink: 0
              }}>
                <item.icon size={24} color="#0369a1" />
              </div>
              <div>
                <h4 style={{ fontSize: 18, fontWeight: 800, color: "#0f172a", margin: "0 0 5px 0" }}>{item.title}</h4>
                <p style={{ fontSize: 14, fontWeight: 500, color: "#64748b", lineHeight: 1.6, margin: 0 }}>
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        <div style={{ 
          marginTop: 50, 
          padding: 20, 
          backgroundColor: "#f1f5f9", 
          borderRadius: 15,
          borderLeft: "5px solid #0369a1"
        }}>
          <p style={{ fontSize: 12, fontWeight: 600, color: "#475569", margin: 0, lineHeight: 1.5 }}>
            <span style={{ color: "#0369a1", fontWeight: 800 }}>NOTE:</span> This report is synthesized from historical symptom logs recorded between <span style={{ color: "#0f172a", fontWeight: 800 }}>{data.period.dateA}</span> and <span style={{ color: "#0f172a", fontWeight: 800 }}>{data.period.dateB}</span>.
          </p>
          <p style={{ fontSize: 12, fontWeight: 600, color: "#475569", marginTop: 10, lineHeight: 1.5 }}>
            All insights are generated by CogniCare's AI clinical assistant to support professional medical evaluation.
          </p>
        </div>
      </div>
    </PageShell>
  );
};
