import { test, expect } from '@playwright/test';

test.setTimeout(120000);

test('test', async ({ page }) => {
  await page.goto('https://cognicare-rosy.vercel.app');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'name@example.com' }).click();
  await page.getByRole('textbox', { name: 'name@example.com' }).fill('patient1@test.com');
  await page.getByRole('textbox', { name: 'name@example.com' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('patient1@One');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForURL('https://cognicare-rosy.vercel.app/brain-dump');
  await page.getByPlaceholder(/How are you feeling/).fill('I am feeling dizzy today');
  await page.getByRole('button', { name: 'Process Written Entry' }).click();
//   await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('link', { name: 'Logs' }).click();
  await page.getByRole('button', { name: 'week' }).click();
  await page.getByRole('button', { name: 'month' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button', { name: '13', exact: true }).first().click();
  await page.waitForLoadState('networkidle');
  await page.locator('text=ADDED BY CARER 2').first().waitFor({ state: 'visible', timeout: 10000 });
  const discussBtn = page.locator('button:has-text("Discuss")').first();
  await expect(discussBtn).toBeVisible({ timeout: 15000 });
  await discussBtn.click();
  await page.getByRole('textbox', { name: 'Share your message...' }).click();
  await page.getByRole('textbox', { name: 'Share your message...' }).fill('and for today as well');
  await page.getByRole('button').nth(1).click();
  await page.getByRole('button').first().click();
  await page.getByRole('heading', { name: /Ref:.*13\/4/ }).click();
  await page.getByRole('button').first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });
  await page.getByRole('button', { name: 'Resolve' }).nth(1).click();
  await page.getByRole('button', { name: 'Contacts' }).click();
  await page.getByRole('button', { name: 'Start Chatting' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Share your message...' }).click();
  await page.getByRole('textbox', { name: 'Share your message...' }).fill('HI');
  await page.getByRole('button').nth(1).click();
  await page.getByRole('button').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Hotline' }).click();
  const page1 = await page1Promise;
  await page1.waitForLoadState('networkidle');
  await page1.getByTestId('countryInput').click();
  const ukOption = page1.getByRole('option', { name: /United Kingdom/i });
  await ukOption.waitFor({ state: 'visible', timeout: 10000 });
  await ukOption.click();
   await page.getByRole('link', { name: 'Insights' }).click();
   await expect(page.getByText('Getting AI Insights')).not.toBeVisible({ timeout: 60000 });
  await page.getByRole('button', { name: '15 Days' }).click();
  await expect(page.getByText('Getting AI Insights')).not.toBeVisible({ timeout: 60000 });
  await page.locator('g:nth-child(2) > .recharts-rectangle').click();
  await page.locator('g:nth-child(5) > .recharts-rectangle').click();
  await page.getByRole('button', { name: 'See AI Insights' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'See Predictive Analysis' }).click();
  await expect(page.getByText('7-Day Health Outlook')).toBeVisible({ timeout: 15000 });
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'here' }).click();
  await page.getByRole('button', { name: 'Understood' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button', { name: 'Export Data' }).click();
  page.waitForEvent('popup');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download (AI PDF)' }).click();
  await downloadPromise;
  await page.getByRole('button', { name: 'Export Data' }).click();
  await page.getByRole('button', { name: 'Export Doc Form' }).click();
  await page.getByRole('textbox', { name: 'Years' }).click();
  await page.getByRole('textbox', { name: 'Years' }).fill('33');
  await page.getByRole('textbox', { name: 'Full name' }).click();
  await page.getByRole('textbox', { name: 'Full name' }).fill('Patient 1');
  const nextStep = page.getByRole('button', { name: 'Next Step' });
  await expect(nextStep).toBeEnabled({ timeout: 10000 });
  await nextStep.click();
  await page.getByRole('textbox', { name: 'Enter response here…' }).first().click();
  await page.getByRole('textbox', { name: 'Enter response here…' }).first().fill('no');
  await page.getByRole('textbox', { name: 'Enter response here…' }).first().press('Tab');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(1).fill('yes');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(1).press('Tab');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(2).fill('no');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(2).press('Tab');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(3).fill('normal');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(3).press('Tab');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(4).fill('yes');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(4).press('Tab');
  await page.getByRole('textbox', { name: 'Enter response here…' }).nth(5).fill('normal');
  await page.getByRole('button', { name: 'Next Step' }).click();
  await page.getByText('≥4 concussions or mild TBIs').first().click();
  await page.locator('div:nth-child(3) > .w-\\[20px\\]').first().click();
  await page.getByText('Bradykinesia').click();
  await page.getByText('Gait change').click();
  await page.getByRole('button', { name: 'Next Step' }).click();
  await page.getByText('I may not be able to endure a').first().click();
  await page.getByRole('button', { name: 'Next Step' }).click();
  const page3Promise = page.waitForEvent('popup');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download PDF' }).click();
  await page3Promise;
  await download1Promise;
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'Manage Carer Access Control' }).click();
  await page.locator('.p-2').first().click();
  await page.locator('div').filter({ hasText: 'Symptom RecordsAllow viewing' }).nth(2).click();
  await page.getByRole('switch').first().click();
  await page.getByRole('button', { name: 'Save Permissions' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
});