export const DOC_FORM_STRINGS = {
  GENERAL: {
    APP_NAME: "CTE Health Monitor",
    DOC_FORM_TITLE: "Doctor Navigation Form",
    CONFIDENTIAL: "Confidential",
    PAGE: "Page",
    OF: "of",
    LOGS_SUFFIX: "months since logs",
    BTN_GENERATING: "Generating...",
    BTN_DOWNLOAD_PDF: "Download PDF",
    NOT_ANSWERED: "Not answered",
    NOT_RECORDED: "Not recorded",
    PART_1: "Part 1",
    PART_2: "Part 2",
    AI_EVALUATED: "✦ AI Evaluated Content",
    FIELDS_COMPLETED: "7/7 fields completed"
  },
  PATIENT_INFO: {
    SECTION_TITLE: "🧑⚕️ Patient Information",
    LABEL_NAME: "Patient Name",
    PLACEHOLDER_NAME: "Full name",
    LABEL_AGE: "Age",
    PLACEHOLDER_AGE: "Years",
    LABEL_CONSULTANT: "Consultant",
    PLACEHOLDER_CONSULTANT: "Dr. Name",
    LABEL_EVAL_DATE: "Date of Evaluation",
    PLACEHOLDER_EVAL_DATE: "DD/MM/YYYY",
  },
  SYMPTOMS: {
    SECTION_TITLE: "✅ Symptom Checklist",
    SUBTITLE: "Tap a symptom to mark it present, then set duration and trend.",
    MARKED: "marked",
    INCOMPLETE: "Incomplete selection",
    DURATION: "Duration",
    RECENT: "Recent (<6 mo)",
    SIX_MONTHS_PLUS: "6 Months+",
    CLINICAL_TREND: "Clinical Trend",
    IMPROVING: "Improving",
    SAME: "Same",
    WORSENING: "Worsening",
    STAYING_SAME: "Staying Same",
    GETTING_WORSE: "Getting Worse",
    REPORT_PART_1: "Symptom Report (1/2)",
    REPORT_PART_2: "Symptom Report (2/2)",
    PRESENT_OUT_OF: "present out of",
    TOTAL_ASSESSED: "total assessed",
    SYMPTOM_HEADER: "Symptom",
    CONTINUED_FROM: "Continued from Page 1"
  },
  HISTORY: {
    SECTION_TITLE: "Patient History",
    RESPONSE_REQUIRED: "Response Required",
    PLACEHOLDER: "Enter response here…",
  },
  TES: {
    SECTION_TITLE: "TES Criteria Assessment",
    SECTION_RHI: "History of Repetitive Head Impacts",
    RHI_SUBTITLE: "≥1 must be met",
    RHI_NOTES: "RHI Notes",
    RHI_PLACEHOLDER: "e.g. 9 years contact sports, 3 recorded concussions",
    SECTION_CORE: "Core Clinical Features",
    CORE_SUBTITLE: "≥1 must be present",
    SECTION_SUPPORTIVE: "Supportive Features",
    SUPPORTIVE_SUBTITLE: "≥2 must be present",
    SECTION_DURATION: "Duration of Clinical Features",
    DURATION_SUBTITLE: "Minimum 12 months",
    DURATION_LABEL: "Duration Summary",
    DURATION_PLACEHOLDER: "Describe duration of symptoms",
  },
  DIAGNOSTICS: {
    SECTION_SUBTYPE: "Diagnostic Subtype",
    SUBTYPE_SUBTITLE: "Select 1",
    SELECTION_REQUIRED: "Selection Required",
    MOTOR_FEATURES: "Motor Features (≥1)",
    CLINICAL_COURSE: "Clinical Course",
  },
  CTE: {
    SECTION_TITLE: "CTE Likelihood",
    SUBTITLE: "Select 1",
    NOTICE: "Requires imaging and biomarker results — cannot be inferred from symptom logs. Leave blank until clinical data is available.",
  },
  CONCERNS: {
    SECTION_TITLE: "🏥 Environment & Care Suggestions",
    SUBTITLE: "Select accommodations to be included in the PDF report.",
    PROVIDER_LABEL: "Patient Concerns — For Healthcare Provider",
  },
  SUMMARY: {
    SECTION_TITLE: "Overall Severity Score",
    SUBTITLE_URGENCY: "Urgency and Recommendations",
    URGENCY_HIGH: "Requires urgent clinical attention. Multiple TES criteria met. Escalate to neurologist immediately.",
    URGENCY_MODERATE: "Significant combined burden. Specialist referral is recommended. Monitor closely.",
    URGENCY_MILD: "Some criteria met. Continued monitoring and full clinical assessment recommended.",
    URGENCY_INSUFFICIENT: "Insufficient data — complete all sections for an accurate assessment.",
    LEVEL_HIGH: "High Severity",
    LEVEL_MODERATE: "Moderate",
    LEVEL_MILD: "Mild",
    LEVEL_INSUFFICIENT: "Insufficient",
    SOURCES_HP: "Patient History",
    SOURCES_SB: "Symptom Burden",
    SOURCES_TC: "TES Criteria",
    DISCLAIMER: "This form was generated from patient self-reported symptom data via CTE Health Monitor. It is intended to support clinical conversations and should not replace professional medical assessment.",
    VIEW_TITLE: "📋 Patient Summary & Next Steps",
    VIEW_DESC: "The data above is ready for exporting. Click Download below to generate the clinical navigation report for your provider.",
    SEVERITY_CONCERNS: "Severity & Concerns",
    STATS_PRESENT: "present",
    STATS_WORSE: "worse",
    STATS_RHI: "RHI",
    STATS_CORE: "Core",
    STATS_SUP: "Sup",
  },
  PREFILL: {
    LOADING_TITLE: "Auto-filling form",
    LOADING_MSG_INITIAL: "Mapping symptoms to criteria…",
    LOADING_MSG_TES: "Mapping symptoms to TES criteria…",
    ERROR_MISSING_ID: "Missing patient ID.",
    ERROR_FAILED: "Auto-fill failed — please fill in manually.",
    SUCCESS_BOLD: "Form pre-filled",
    SUCCESS_TEXT: "from logs. Fields marked",
    SUCCESS_SUFFIX: "were inferred."
  },
  NAVIGATION: {
    BTN_BACK: "Back",
    BTN_NEXT: "Next Step"
  }
};
