export const EXPORT_STRINGS = {
  MENU: {
    LABEL_EXPORT: "Export Data",
    STATUS_EXPORTING: "Exporting...",
    STATUS_ANALYZING: "Analyzing symptoms...",
    STATUS_CACHED: "Using cached report data...",
    STATUS_CREATING_PDF: "Creating PDF...",
    STATUS_COMPLETE: "Complete!",
    ITEM_DOWNLOAD_AI: "Download (AI PDF)",
    ITEM_EXPORT_FORM: "Export Doc Form",
    TOOLTIP_LOGS: "Requires 1 month of logs",
    ERROR_PDF_CAPTURE: "Failed to capture PDF",
    ERROR_GENERATE_REPORT: "Failed to generate report. Please try again.",
  },
  REPORT: {
    TITLE_HEALTH_MONITOR: "CTE Health Monitor",
    TITLE_SOURCE_CATEGORIZED: "Source-Categorized Health Report",
    DESC_SOURCE_CATEGORIZED: "Differentiating between Patient-reported and Carer-reported symptom severity",
    SUBTITLE_OVERALL_ANALYSIS: "Overall Symptom Analysis — Multi-Source View",
    SUBTITLE_SINGLE_DAY: "Single Day Analysis",
    SUBTITLE_AI_INSIGHTS: "AI Insights — Perception Alignment",
    SUBTITLE_SOURCE_COMPARISON: "Source Comparison Analysis",
    
    LABEL_PATIENT: "Patient",
    LABEL_CARER: "Carer",
    LABEL_PATIENT_UPPER: "PATIENT",
    LABEL_CARER_UPPER: "CARER",
    LABEL_LOGS: "logs",
    LABEL_PAGE: "Page",
    LABEL_PERCEPTION_GAP: "Perception Gap",
    LABEL_ALIGNMENT: "Alignment",
    LABEL_MARKED: "marked",
    LABEL_AVG_VALUE: "avg",
    LABEL_PILLAR: "Pillar",
    LABEL_GAP: "P vs C Gap",
    LABEL_CHANGE: "CHANGE",
    LABEL_WORSENED_UPPER: "WORSENED",
    LABEL_IMPROVED_UPPER: "IMPROVED",
    LABEL_BIGGEST_WORSENING: "BIGGEST WORSENING",
    LABEL_MOST_IMPROVED: "MOST IMPROVED",
    LABEL_BREAKDOWN_PILLAR: "Multi-Source Breakdown by Pillar",
    LABEL_AVG_IMPROVEMENT: "Avg Improvement",
    
    TEXT_BURDEN_BY_PILLAR: "Overall Symptom Burden by Pillar",
    TEXT_BURDEN_DESC: "Percentage contribution of each pillar to total symptom load since",
    TEXT_TREND_TITLE: "6-Month Trend per Pillar",
    TEXT_PILLAR_OVERVIEW: "PILLAR OVERVIEW",
    
    LABEL_AI_INSIGHTS_PERC: "AI Insights — Perception & Alignment",
    LABEL_DISCUSSION_POINTS: "Discussion Points for Care Team",
    LABEL_DISCUSSION_POINTS_SUB: "AI Insights — Perception Alignment",
    LABEL_SINGLE_DAY_SUB: "Source Comparison Analysis",
    LABEL_HIGHEST: "Highest",
    
    INSIGHT_TYPE_HIGHEST: "Highest Burden",
    INSIGHT_TYPE_MATCH: "Perception Match",
    INSIGHT_TYPE_GAP: "Perception Gap",
    INSIGHT_TYPE_WORSENING: "Worsening Trend",
    INSIGHT_TYPE_PERCEPTION: "Perception",
    INSIGHT_TYPE_ALIGNMENT: "Alignment",
    INSIGHT_TYPE_TREND: "Trend",

    BUTTON_EXPORT: "Export Report",
    STATUS_READY: "✓ Report Ready",
    STATUS_ERROR: "✕ Error Generating",
    STATUS_ANALYZING: "Analyzing data...",
    STATUS_CREATING: "Creating PDF...",
    TEXT_SOURCE_BREAKDOWN: "Source Breakdown",
  }
};
